// SPDX-FileCopyrightText: Steven Ward
// SPDX-License-Identifier: MPL-2.0

/// Replay a duplex call script against Castella::Duplex
/**
* \file
* \author Steven Ward
*
* Reads a line-based script from stdin and replays it against
* \c Castella::Duplex, writing one line per squeeze.  The scripts are
* generated by duplex-diff-fuzz.py, which replays the same script against the
* independent Python model in spec-conformance.py and diffs the two outputs.
* The whole run is batched through one process because the Python model is the
* slow side.  Per-program process startup would be pure overhead.
*
* Script grammar, one op per line, "-" denoting an empty byte string.  A
* program is one generated unit of work: a constructor plus a call sequence
* ending in at least one squeeze.
*
*     program <id>                 begin a program (echoed back)
*     new     <C> <rounds> <suffix> <hex N> <hex S>
*     add     <hex>                add(byte string)
*     addle   <hex>                add_left_encoded(byte string)
*     addre   <hex>                add_right_encoded(byte string)
*     addlei  <uint>               add_left_encoded(integer)
*     addrei  <uint>               add_right_encoded(integer)
*     pad                          apply_padding_rule()
*     squeeze <n>                  squeeze_bytes(n), writes "out <hex>"
*
* Blank lines and lines beginning with '#' are ignored.
*/

#include "as_byte_span.hpp"
#include "bytes_to_hex.hpp"
#include "castella-duplex.hpp"
#include "parse_int.hpp"

#include <cstddef>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <exception>
#include <iostream>
#include <memory>
#include <print>
#include <sstream>
#include <stdexcept>
#include <string>
#include <string_view>
#include <system_error>
#include <type_traits>

/// Convert a hexadecimal character to its nibble value
/**
* The inverse of \c nibble_char in bytes_to_hex.hpp, which maps a nibble to a
* lowercase hexadecimal character.  This direction additionally accepts
* uppercase, and validates rather than assuming a precondition.
*
* \param c the hexadecimal character to convert
* \return the value of \a c, in the interval <code>[0, 15]</code>
* \exception std::invalid_argument if \a c is not a hexadecimal digit
*/
[[nodiscard]] static uint8_t
hex_nibble(const char c)
{
    if (c >= '0' && c <= '9')
        return static_cast<uint8_t>(c - '0');
    if (c >= 'a' && c <= 'f')
        return static_cast<uint8_t>(c - 'a' + 10);
    if (c >= 'A' && c <= 'F')
        return static_cast<uint8_t>(c - 'A' + 10);
    throw std::invalid_argument("not a hex digit");
}

/// Decode a hexadecimal script field into the bytes it represents
/**
* The inverse of \c bytes_to_hex in bytes_to_hex.hpp: two hexadecimal
* characters of \a hex become one byte of the result.  The script spells the
* empty byte string as "-", because a zero-length field cannot be read from a
* whitespace-delimited line.
*
* The bytes are carried in a \c std::string rather than a
* <code>std::vector<std::byte></code> because \c std::string::data() is never
* null, even when the string is empty.  An empty vector's \c data() may be
* null.  The \c add_left_encoded and \c add_right_encoded span overloads treat
* a null data pointer as a no-op, which is a C++-side API convenience with no
* counterpart in the specification or the Python model.  Without the string it
* would show up as a spurious divergence on every empty-payload program.
*
* \param hex the hexadecimal characters to decode, or "-" for no bytes
* \return the decoded bytes
* \exception std::invalid_argument if \a hex has an odd length or holds a
*            character that is not a hexadecimal digit
*/
[[nodiscard]] static std::string
hex_to_bytes(const std::string_view hex)
{
    if (hex == "-")
        return {};

    if ((std::size(hex) % 2) != 0)
        throw std::invalid_argument("hex string has an odd length");

    std::string result;
    result.reserve(std::size(hex) / 2);

    for (size_t i = 0; i < std::size(hex); i += 2)
    {
        const auto hi = hex_nibble(hex[i]);
        const auto lo = hex_nibble(hex[i + 1]);
        result.push_back(static_cast<char>((hi << 4) | lo));
    }

    return result;
}

/// Read one whitespace-delimited field, or throw
/**
* Integer fields go through \c parse_int rather than \c operator>>.  For an
* unsigned \a T, \c operator>> silently wraps a negative value and stops at
* the first character it cannot use, so it would accept "-1" as 2^64-1 and
* "1.5" as 1.  \c parse_int rejects both.  It also separates a malformed field
* from one that is merely out of range, so the message names the actual
* problem instead of reporting every failure as a missing field.
*
* \tparam T the field's type (\c std::string for a token, otherwise an integer)
* \param iss the line being interpreted
* \param what the field's name, for the error message
* \return the field's value
* \exception std::invalid_argument if the field is absent, malformed, or out
*            of range for \a T
*/
template <typename T>
[[nodiscard]] static T
read_field(std::istringstream& iss, const char* const what)
{
    std::string token;
    if (!(iss >> token))
        throw std::invalid_argument(std::string("missing field: ") + what);

    if constexpr (std::is_same_v<T, std::string>)
    {
        return token;
    }
    else
    {
        const auto value = parse_int<T>(token);
        if (!value)
        {
            const auto* const why = (value.error() == std::errc::result_out_of_range)
                                        ? "field out of range: "
                                        : "malformed field: ";
            throw std::invalid_argument(why + std::string(what) + " = " + token);
        }
        return *value;
    }
}

// NOLINTNEXTLINE(bugprone-exception-escape)
int main([[maybe_unused]] int argc, [[maybe_unused]] char* argv[])
{
    // Decouple std::cin from C stdio.  The driver spends more time parsing
    // lines than hashing, so stdin throughput sets its runtime.  A 152k-line
    // script runs about 2.8 times faster with this call (0.08 s against
    // 0.22 s).  Output goes through std::println (C stdio) and nothing else
    // reads stdin, so decoupling is safe.
    std::ios::sync_with_stdio(false);

    std::unique_ptr<Castella::Duplex> duplex;
    std::string line;
    int lineno = 0;

    try
    {
        while (std::getline(std::cin, line))
        {
            ++lineno;

            std::istringstream iss(line);
            std::string op;

            if (!(iss >> op) || op.starts_with('#'))
                continue;

            if (op == "program")
            {
                // Every program declares its own duplex.  Without this, a
                // program missing its "new" would silently continue the
                // previous one and report its digests under the new id.
                duplex.reset();
                std::println("program {}", read_field<std::string>(iss, "id"));
                continue;
            }

            if (op == "new")
            {
                const auto capacity_blocks = read_field<int>(iss, "C");
                const auto num_rounds = read_field<int>(iss, "rounds");
                const auto input_suffix = read_field<int>(iss, "suffix");
                const auto function_name =
                    hex_to_bytes(read_field<std::string>(iss, "N"));
                const auto customization_str =
                    hex_to_bytes(read_field<std::string>(iss, "S"));

                duplex = std::make_unique<Castella::Duplex>(
                    capacity_blocks, num_rounds, input_suffix, function_name,
                    customization_str);
                continue;
            }

            if (!duplex)
                throw std::logic_error("op before new");

            if (op == "add")
            {
                const auto data = hex_to_bytes(read_field<std::string>(iss, "hex"));
                duplex->add(as_byte_span(data));
            }
            else if (op == "addle")
            {
                const auto data = hex_to_bytes(read_field<std::string>(iss, "hex"));
                duplex->add_left_encoded(as_byte_span(data));
            }
            else if (op == "addre")
            {
                const auto data = hex_to_bytes(read_field<std::string>(iss, "hex"));
                duplex->add_right_encoded(as_byte_span(data));
            }
            else if (op == "addlei")
            {
                duplex->add_left_encoded(read_field<uint64_t>(iss, "uint"));
            }
            else if (op == "addrei")
            {
                duplex->add_right_encoded(read_field<uint64_t>(iss, "uint"));
            }
            else if (op == "pad")
            {
                duplex->apply_padding_rule();
            }
            else if (op == "squeeze")
            {
                const auto n = read_field<int>(iss, "n");
                const auto digest = duplex->squeeze_bytes(n);
                std::println("out {}", bytes_to_hex(digest));
            }
            else
            {
                throw std::invalid_argument("unknown op: " + op);
            }
        }
    }
    catch (const std::exception& e)
    {
        // Flush the results already written before reporting on stderr.
        (void)std::fflush(stdout);
        std::println(stderr, "error: line {}: {}", lineno, e.what());
        return EXIT_FAILURE;
    }

    return EXIT_SUCCESS;
}
