// SPDX-FileCopyrightText: Steven Ward
// SPDX-License-Identifier: MPL-2.0

/// Castella round constants and permutation function
/**
* \file
* \author Steven Ward
*/

#pragma once

#include "aes.hpp"
#include "simd_load.hpp"
#include "simd_transpose.hpp"
#include "simd_types.hpp"

#include <array>
#if defined(DEBUG)
#include <cassert>
#endif
#include <cstdint>
#include <ranges>
#include <span>

namespace Castella
{

using block_t = uint8x16_t;

#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wignored-attributes"

template <size_t N>
using arr_blocks = std::array<block_t, N>;

#pragma GCC diagnostic pop

// This macro is only defined in certain test programs to find the optimum
// minimum round count.
#if !defined(DEFAULT_CASTELLA_NUM_ROUNDS_MIN)
#define DEFAULT_CASTELLA_NUM_ROUNDS_MIN 3 // NOLINT(cppcoreguidelines-macro-usage)
#endif

inline constexpr int NUM_ROUNDS_MIN = DEFAULT_CASTELLA_NUM_ROUNDS_MIN;

#undef DEFAULT_CASTELLA_NUM_ROUNDS_MIN

#if !defined(DEFAULT_CASTELLA_NUM_ROUNDS_MAX)
// Embiggen the value as needed.
#define DEFAULT_CASTELLA_NUM_ROUNDS_MAX 16 // NOLINT(cppcoreguidelines-macro-usage)
#endif

inline constexpr int NUM_ROUNDS_MAX = DEFAULT_CASTELLA_NUM_ROUNDS_MAX;

#undef DEFAULT_CASTELLA_NUM_ROUNDS_MAX

static_assert(NUM_ROUNDS_MIN <= NUM_ROUNDS_MAX);

/// Create the first \a N Castella round constants
/**
* The first Castella round constant is <q>expand 16-byte c</q>.
* Each subsequent Castella round constant is generated by performing 1 round of
* AES encryption (with a zero round key) on the preceding one.
*/
template <int N>
static auto
create_round_constants() noexcept
{
    static_assert(N > 0);

    arr_blocks<N> result;

    // It's a perfectly cromulent initial value.
    const auto rc_0 = simd_load16("expand 16-byte c");

    result[0] = rc_0;

    for (decltype(N) i = 1; i < N; ++i)
    {
        result[i] = aes_enc_0(result[i-1]);
    }

    return result;
}

/// The Castella round constants
// {{{
/**
* ## _MakingOfKeccak.pdf_
*
* ### 7.4 The hermetic sponge strategy
* #### Page 21
*
* <blockquote>
* There needs to be some asymmetry between the rounds to avoid slide attacks.
* This can be addressed by including the addition of round constants that differ
* from round to round to the state.  These constants may also provide asymmetry
* to the round function to avoid symmetric properties (see Section 8).
* </blockquote>
*
* ### 8.7 The round constants
* #### Page 27
*
* <blockquote>
* The round constants are there to disrupt symmetry, both in the temporal as in
* the three spatial dimensions.  …  The bits of the round constants are different
* from round to round and are taken as the output of a maximum-length eight-bit
* linear feedback shift register.
* </blockquote>
*/
// }}}
inline const auto round_constants = create_round_constants<NUM_ROUNDS_MAX>();

/// The Castella permutation function
// {{{
/**
* \param state the state to permute
* \param num_rounds the number of rounds to perform
* \pre \a N ∈ {2, 4, 8, 16}
* \pre \a num_rounds ≥ \c NUM_ROUNDS_MIN
* \pre \a num_rounds ≤ \c NUM_ROUNDS_MAX
* Each round consists of the following steps:
*   1. Apply (via XOR) the round constant to the first element of the state array.
*   2. Perform 3 rounds of AES encryption (with a zero round key) on each
*      element of the state array.
*   3. Transpose the state, treating it as a _NxN_ matrix of _(128/N)-bit_
*      integers.
*
*
* ## _JDA_VRI_Rijndael_2002.pdf_
* ### 3.5 The Number of Rounds
* #### Page 41 (56)
*
* <blockquote>
* Two rounds of Rijndael provide 'full diffusion' in the following sense: every
* state bit depends on all state bits two rounds ago, or a change in one state
* bit is likely to affect half of the state bits after two rounds.
* </blockquote>
* \sa https://crypto.stackexchange.com/questions/44532/how-2-rounds-in-aes-achieve-full-diffusion
*/
// }}}
template <size_t N>
static void
permute(arr_blocks<N>& state, const int num_rounds) noexcept
{
    static_assert((N == 2) || (N == 4) || (N == 8) || (N == 16));

#if defined(DEBUG)
    assert(num_rounds >= NUM_ROUNDS_MIN);
    assert(num_rounds <= NUM_ROUNDS_MAX);
#endif

    constexpr int aes_num_rounds = 3;

    for (const auto& rc : std::span{round_constants}.first(num_rounds))
    {
        state[0] ^= rc;
        aes_enc_0_arr<aes_num_rounds>(state);
        simd_transpose(state);
    }
}

/// The inverse Castella permutation function
// {{{
/**
* \param state the state to permute
* \param num_rounds the number of rounds to perform
* \pre \a N ∈ {2, 4, 8, 16}
* \pre \a num_rounds ≥ \c NUM_ROUNDS_MIN
* \pre \a num_rounds ≤ \c NUM_ROUNDS_MAX
* Rounds are performed in reverse order, and each round consists of the following
* steps (in reverse order of \c permute):
*   1. Transpose the state, treating it as a _NxN_ matrix of _(128/N)-bit_
*      integers.
*   2. Perform 3 inverse rounds of AES encryption (with a zero round key) on
*      each element of the state array.
*   3. Apply (via XOR) the round constant to the first element of the state array.
*/
// }}}
template <size_t N>
static void
permute_inv(arr_blocks<N>& state, const int num_rounds) noexcept
{
    static_assert((N == 2) || (N == 4) || (N == 8) || (N == 16));

#if defined(DEBUG)
    assert(num_rounds >= NUM_ROUNDS_MIN);
    assert(num_rounds <= NUM_ROUNDS_MAX);
#endif

    constexpr int aes_num_rounds = 3;

    for (const auto& rc : std::span{round_constants}.first(num_rounds) | std::views::reverse)
    {
        simd_transpose(state);
        aes_enc_0_inv_arr<aes_num_rounds>(state);
        state[0] ^= rc;
    }
}

} // namespace Castella
